### ISSUE TITLE
Uncaught ReflectionException: Class cache does not exist

### ISSUE THREAD

**Issue by celorodovalho** [GrahamCampbell/Laravel-GitHub#102]
An error is throwing if I try to use with Laravel 6+
```
PHP Fatal error:  Uncaught ReflectionException: Class cache does not exist in / var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php:803
Stack trace:
#0 / var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(803): ReflectionClass->__construct('cache')
#1 / var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\Container\Container->build('cache')
#2 / var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->resolve('cache', Array)
#3 / var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): Illuminate\Container\Container->make('cache', Array)
#4 / var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(1245): Illuminate\Foundation\Application->make('cache')
#5 / var/www/vendor/graham-campbell/github/src/Git in / var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 805
```

### \GrahamCampbell\GitHub\GitHubServiceProvider::registerGitHubFactory
```
    protected function registerGitHubFactory()
    {
        $this->app->singleton('github.factory', function (Container $app) {
            $auth = $app['github.authfactory'];
            $cache = $app['cache'];

            return new GitHubFactory($auth, $cache);
        });

        $this->app->alias('github.factory', GitHubFactory::class);
    }
```
## Sugestion:
\GrahamCampbell\GitHub\GitHubServiceProvider::registerGitHubFactory line 94
```
            $cache = null;
            if ($app->has('cache')) {
                $cache = $app['cache'];
            }
```
\GrahamCampbell\GitHub\GitHubFactory::__construct line 70
```
public function __construct(AuthenticatorFactory $auth, ?Factory $cache)
```

**Comment by GrahamCampbell** [comment]
Yeh, I wondered about this, but actually the contracts component is required, so it is expected that you provide an implementation of the cache contract. Unfortunately, Laravel doesn't have separate contracts packages for components, or virtual packages to mandate implementation.

**Comment by GrahamCampbell** [comment]
> An error is throwing if I try to use with Laravel 6+

I'm not able to replicate this with laravel/framework 6.x myself?

**Comment by celorodovalho** [comment]
I'm trying to inject the GithubManager class in \App\Exceptions\Handler constructor.
Why? Because I'm sending some exceptions as issues to my Github repo.
Everything works perfectly until I try to run "composer update", then I realize there are some errors during the instalation, Laravel tries to handle this errors, but because my implementation it goes through GithubManager first... soooooo there is no cache implementation in that moment.
Even I comment my code just to install, the error happens again in any Laravel commands (if there is a error before).
So, if it's possible to check if already exists a cache implementation before to handle it.

I already applied a local patch over composer, but I just want to let you know if there something possible to do about that.

**Comment by GrahamCampbell** [comment]
That's probably it. Instead, resolve it using the app helper within the handler when you need it, at runtime.
