### ISSUE TITLE
GitHub depreciating OAuth via query string

### ISSUE THREAD

**Issue by judge2020** [GrahamCampbell/Laravel-GitHub#103]
See [this issue](https://github.com/KnpLabs/php-github-api/issues/847) for the GH library this depends upon - GH is depreciating authentication via the query string and suggests HTTP Basic auth. For this laravel library, the `ApplicationAuthenticator` currently uses the depreciated method.

https://github.com/GrahamCampbell/Laravel-GitHub/blob/aacf35dd9b9782115c9a6a483ed61a74189bbb24/src/Authenticators/ApplicationAuthenticator.php#L45

From the above-linked issue, a drop-in fix *should be* changing the `authMethod` from `AUTH_URL_CLIENT_ID` to `AUTH_HTTP_PASSWORD`, however, this doesn't work for me (getting 'bad credentials') so I'm opening an issue instead of a PR.

**Comment by mattstauffer** [comment]
(For those wondering, I think the intended link was this: https://github.com/KnpLabs/php-github-api/issues/847 )

**Comment by judge2020** [comment]
@mattstauffer Thanks, edited.

**Comment by GrahamCampbell** [comment]
Thanks. I was aware of this issue too. I will provide a fix within the next 30 days. This doesn't seem to be a major issue, since they have only deprecated support for now, and not removed yet.

**Comment by judge2020** [comment]
> however, this doesn't work for me (getting 'bad credentials') so I'm opening an issue instead of a PR.

To update on this, I made a mistake. If you pass bad credentials with the old `AUTH_URL_CLIENT_ID`, GitHub doesn't 401 the request (you're effectively still in anonymous mode), but it does with Basic Auth. I imagine some might get errors with this update, but only if their application credentials are already bad. The patch works for me with correct credentials.

**Comment by GrahamCampbell** [comment]
Sounds fine. The new behaviour sounds better tbh. ;)

**Comment by GrahamCampbell** [comment]
Thanks for confirming the patch worked.
