### ISSUE TITLE
Code usage to merge a PR

### ISSUE THREAD

**Issue by cloudelabs** [GrahamCampbell/Laravel-GitHub#108]
I have created an issue on the other repo asking for Merge a PR documentation. They have responded but I'm not sure how to use it in the code. I need your help here,

https://github.com/KnpLabs/php-github-api/issues/866

All I want to do is merge a PR to Master branch.

**Comment by GrahamCampbell** [comment]
Yeh, it's possible to merge a PR, and @acrobat showed you the code 18 hours ago on that issue.
