### ISSUE TITLE
l4 publish asstes namespace not found

### ISSUE THREAD

**Issue by mms-hamburg** [GrahamCampbell/Laravel-GitHub#11]
./artisan vendor:publish
                                                          
  [InvalidArgumentException]                                
  There are no commands defined in the "vendor" namespace. 

any suggestions or hints? running laravel 4.2

**Comment by GrahamCampbell** [comment]
You can't be running laravel 4.2 if that's the case. Laravel 4.2 always has that command - nothing to do with my package.
