### ISSUE TITLE
[question] Is there a way to do a query on a subresource? (hypermedia) 

### ISSUE THREAD

**Issue by isaackearl** [GrahamCampbell/Laravel-GitHub#112]
If for example I query a repository, and in that response there is an "issues_url" with the api endpoint required to get the issues for that particular repository... is there a way for me to call that endpoint with the api?  I can't even find a way to do it manually.  

Here is an example of what the query I want looks like:
``` https://api.github.com/repos/GrahamCampbell/Laravel-GitHub/issues{/number} ```

I don't see any way to do this with the api... I tried doing it manually like this:
```
$repo = $this->gitHubManager->repository()->showById(14735403); // getting a specific repo
// then trying to get the issues for that specific repo
$issues = $this->gitHubManager->getHttpClient()->get(uri_template($repo['issues_url'], [])); // <-- this doesn't work
```

I'm just checking to see if there is something I'm missing.  

Thanks!
Isaac

**Comment by GrahamCampbell** [comment]
You will need to use the issues API class. You should never need to grab the raw http client like that. There's an example on the README for how to get the issues for a repo. :)

**Comment by GrahamCampbell** [comment]
> $this->gitHubManager->issues()->show('GrahamCampbell', 'Laravel-GitHub', 2);

**Comment by GrahamCampbell** [comment]
Note that GitHub officially require you to address repos by their path, and not their internal ID. That special method that allows you to get a repo by its ID is actually using an undocumented part of their API.

**Comment by isaackearl** [comment]
@GrahamCampbell Oh you are right.  I have no idea how I missed that! thanks!  I  think I was a bit to tired while working on this last night.

**Comment by GrahamCampbell** [comment]
No problem. There's also some documentation for what stuff is available at https://github.com/KnpLabs/php-github-api/tree/master/doc. I think I link that from the README here too. You can also look directly at the source at https://github.com/KnpLabs/php-github-api/tree/master/lib/Github/Api. I find that is often the easiest way to discover what is available (and indeed what is not!).
