### ISSUE TITLE
How to use Page？

### ISSUE THREAD

**Issue by JeffreyBool** [GrahamCampbell/Laravel-GitHub#114]
How to use Page？

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. The result pager documentation is available at https://github.com/KnpLabs/php-github-api/blob/master/doc/result_pager.md, which is linked to from our README. $client = new Github\Client();` in all the upstream examples, will need to be replaced with how you get the client instance using this package (for example `$client = GitHub::connection();`)
