### ISSUE TITLE
Unable to add to new laravel project

### ISSUE THREAD

**Issue by Fuitad** [GrahamCampbell/Laravel-GitHub#121]
Trying to include your package in a fresh laravel project (8.12) is giving me an error.

> composer require graham-campbell/github:^9.5 php-http/guzzle6-adapter:^2.0
> ./composer.json has been updated
> Running composer update graham-campbell/github php-http/guzzle6-adapter
> Loading composer repositories with package information
> Updating dependencies
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - php-http/guzzle6-adapter[dev-master, v2.0.0, ..., v2.0.1] require guzzlehttp/guzzle ^6.0 -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1).
>     - php-http/guzzle6-adapter 2.x-dev is an alias of php-http/guzzle6-adapter dev-master and thus requires it to be installed too.
>     - Root composer.json requires php-http/guzzle6-adapter ^2.0 -> satisfiable by php-http/guzzle6-adapter[v2.0.0, v2.0.1, 2.x-dev (alias of dev-master)].
> 
> Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
> 
> Installation failed, reverting ./composer.json and ./composer.lock to their original content.

Is there something different I should be doing?

**Comment by exzachlyvv** [comment]
```composer require graham-campbell/github:^9.5 php-http/guzzle7-adapter```

worked for me

**Comment by GrahamCampbell** [comment]
Guzzle 7 is not officially supported yet. You can use Guzzle 6 until the next major version of this package is tagged (which will be in the next few weeks).
