### ISSUE TITLE
Private Repos

### ISSUE THREAD

**Issue by InQbate** [GrahamCampbell/Laravel-GitHub#124]
Hi,

Cant find good documentation with regards to creating a connection to a private account. I have setup a GitHub App.
Downloaded the PEM, and setup config:

```
        'private' => [
            'method'     => 'private',
            'appId'      => '90711',
            'keyPath'    => base_path('/config/github.private-key.pem'),
```

Calling an endpoint using `GitHub::connection('private')`  always results in a Bad Credentials / Unauthorized. I have tried API 3 and 4. 

Any idea how to get this working?

**Comment by GrahamCampbell** [comment]
I'm not sure. It should work as documented. If you'd like to purchase some paid support, you can do so at the above link. Otherwise, I'm not sure there's much I can do for you, since the issue seems to be application specific.

**Comment by pkeogan** [comment]
same issue

**Comment by flavio-paqt** [comment]
Same issue here.

**Comment by rachid-aachich** [comment]
same issue

**Comment by themustafaomar** [comment]
Still not working :(

```php
Github::connection('private')->apps()->listRepositories('USER_ID');
```
