### ISSUE TITLE
How to switch connection at runtime and assign a new connection when the rate limit has been exceeded.

### ISSUE THREAD

**Issue by lyricxmint** [GrahamCampbell/Laravel-GitHub#139]
**PHP version**: 7.4
**Laravel version**: 8

**Description**

Hi @GrahamCampbell  
Thanks for introducing this awesome library. I just started to use this and I got stuck in a scenario where I need to increase the rate limit of API. I am using tokens for authentication. But every token has limited to 5k requests per hour. To overcome this problem I have created different tokens and inserted it in the config file like below - 

**My connection file setting in github.php -**

```
'default' => 'main',

'connections' => [
    'main' => [
        'method'     => 'token',
        'token'      => '************************'
    ],

    'alternate1' => [
        'method'     => 'token',
        'token'      => '****************************'
    ],

    'alternate2' => [
        'method'     => 'token',
        'token'      => '****************************'
    ]
]
```

**How to switch connection at a run time**

My default connection is "**main**". Now I want to switch connection run time if a connection rate limit is exceeded. I am trying something like below but it does not seem to be working. I don't know the best approach to overcome this problem. Please suggest me something good or please tell me where I am lacking in the below code - 

```
public function getUserDetail($username)
{
    try {
        $userDetail = $this->github->users()->show($username);
        return $userDetail;
    } catch (\RuntimeException $e) {
        $this->github->setDefaultConnection('alternate1');
        $this->getUserDetail($username);
    }
}
```

I am waiting for your response. I am very curious to know how I can switch it and run my application on multiple connections.

Regards,
Salman Ahmad

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. This falls outside of what the issue tracker is for, but I'd still love to help you. If you reach out to me at hello at gjcampbell.co.uk, we can arrange something. :)
