### ISSUE TITLE
Facades doen't get Docblocks for ide-helper

### ISSUE THREAD

**Issue by Slubby** [GrahamCampbell/Laravel-GitHub#144]
when I run `php artisan ide-helper:generate` it doesn't get the method's in the doc blocks. Because you have a tag @author in your facades class.

So ide-helper search first in de alias class (facades class) for doc blocks. ide-helper find the tag @author in the facades class because of that it will not look in the root class (GithubManager) for the other doc blocks.

this is the method from ide-helper and `include_class_docblocks` is true in the config.
```
if ($this->config->get('ide-helper.include_class_docblocks')) {
    // if a class doesn't expose any DocBlock tags
    // we can perform reflection on the class and
    // add in the original class DocBlock
    if (count($this->phpdoc->getTags()) === 0) {
        $class = new ReflectionClass($this->root);

        $this->phpdoc = new DocBlock($class->getDocComment());
    }
}
```

To solve this is by adding the doc blocks methods in your facades class but I read you don't like that #106. Or you can remove the @author tag in the facades class

**Comment by GrahamCampbell** [comment]
What really needs to happen is a fix is made to the ide-helper so it can understand this code. Thanks for taking the time to raise this, all the same. 🍻
