### ISSUE TITLE
Projects V2 API

### ISSUE THREAD

**Issue by SrPeterr** [GrahamCampbell/Laravel-GitHub#146]
Hi!
I'm trying to get the projects for my organization, and it comes up as if I haven't got any, which I have.
`GitHub::organizationProjects()->all('nameoforg');`

It just gives me an empty array, is this because the API is only for the Projects (Classic) API?

**Comment by GrahamCampbell** [comment]
Possibly, it is hard to say. Note that you've opened an issue on the issue tracker of a repo that is a Laravel API wrapper. If you believe there is a bug in the PHP client itself, you could open issue upstream at https://github.com/KnpLabs/php-github-api. If you need free support, the best place to look for that is on a forum of your choice - the issue tracker here is just for bugs in the package. Regarding paid support, I am happy to engage if you ping me an email at hello@gjcmapbell.co.uk or via included support via a [Tidelift subscription](https://tidelift.com/subscription/pkg/packagist-graham-campbell-github?utm_source=packagist-graham-campbell-github&utm_medium=referral&utm_campaign=enterprise&utm_term=repo). GitHub support may also be able to help you if you have an Enterprise subscription.
