### ISSUE TITLE
Support github-api 3.9.*

### ISSUE THREAD

**Issue by iBotPeaches** [GrahamCampbell/Laravel-GitHub#147]
https://github.com/KnpLabs/php-github-api/releases/tag/v3.9.0

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. I am looking into this now. [Sponsoring me](https://github.com/sponsors/GrahamCampbell) can help me prioritize OSS work. I am spread thin across many open source projects including Guzzle.

**Comment by GrahamCampbell** [comment]
[v12.0.0](https://github.com/GrahamCampbell/Laravel-GitHub/releases/tag/v12.0.0) has now been released. 🎉
