### ISSUE TITLE
Laravel 10 Update

### ISSUE THREAD

**Issue by Elliot-putt** [GrahamCampbell/Laravel-GitHub#149]
Laravel 10 Update please when you get chance!

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. I am looking into this now. [Sponsoring me](https://github.com/sponsors/GrahamCampbell) can help me prioritize OSS work. I am spread thin across many open source projects including Guzzle.

**Comment by GrahamCampbell** [comment]
[v12.0.0](https://github.com/GrahamCampbell/Laravel-GitHub/releases/tag/v12.0.0) has now been released. 🎉
