### ISSUE TITLE
How to Get Private Repo Info

### ISSUE THREAD

**Issue by jasonherndon** [GrahamCampbell/Laravel-GitHub#15]
I struggled with this for a few hours since it seemed that a lot of the documentation wasn't that thorough or you had to piece it together... but basically, if you want to use this package to get private repos... here's what I did.

Step 1:
Log in to your github and add a personal access token. Be sure to copy it after it is created.

Step 2:
Configure the alternative (or whichever you'd like) connection with the access token, replacing "your-token" with the copied token from step 1.

Step 3:
$repo = GitHub::connection('alternative')->repo()->show('myusername', 'myprivaterepo');

And done!
Thanks @GrahamCampbell for your work with this package!

**Comment by GrahamCampbell** [comment]
There are other ways to do this. You can use any authentication method.

**Comment by GrahamCampbell** [comment]
The docs are on github's own website. It doesn't change between the software you're using.

**Comment by jasonherndon** [comment]
Totally understood @GrahamCampbell  - my point was not that it was impossible any other way, just that I spent a fair bit of time with the package that yours is a wrapper for, as well as the github docs, and the responses always returned the public repo's only. Plus, for my site, the token method will work best. 

For some reason your wrapper here was the cleanest example of where it just worked exactly as the docs said.
