### ISSUE TITLE
`Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead` message on installation

### ISSUE THREAD

**Issue by binaryfire** [GrahamCampbell/Laravel-GitHub#157]
Hello. Firstly, thanks for your work on this great package.

We're getting a `Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead` warning after installing it. I'm guessing it's because of one of the dependencies. Is there any chance this could be fixed? It's causing our CI/CD security scanner's 'Outdated dependencies' check to fail.

**Comment by antennaio** [comment]
I think this is an issue in upstream dependency:

https://github.com/KnpLabs/php-github-api/issues/1127

**Comment by GrahamCampbell** [comment]
Thanks for the report. This is a very minor issue, and you can safely ignore this, as it will never pose a security issue - interface only packages can't have security issues in them. I imagine this will eventually be fixed, maybe in the next few months. I've created a PR upstream for them to review: https://github.com/KnpLabs/php-github-api/pull/1134.

**Comment by binaryfire** [comment]
> I've created a PR upstream for them to review: https://github.com/KnpLabs/php-github-api/pull/1134.

Thank you! It's more of an issue in CI/CD pipelines which use security scanning. It's not always easy to add exceptions because of compliance reasons.

**Comment by GrahamCampbell** [comment]
This is fixed in today's release.
