### ISSUE TITLE
Package suggests updates

### ISSUE THREAD

**Issue by RyanHipkiss** [GrahamCampbell/Laravel-GitHub#21]
guzzle/guzzle suggests installing guzzlehttp/guzzle (Guzzle 5 has moved to a new package name. The package you have installed, Guzzle 3, is deprecated.)

knplabs/github-api suggests installing knplabs/gaufrette (Needed for optional Gaufrette cache)

paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)

Would these be able to be updated?

**Comment by vinkla** [comment]
This should be moved to [KnpLabs/php-github-api](https://github.com/KnpLabs/php-github-api). This package doesn't suggest any of those packages. It is this package dependencies who is in control of suggestion what you should install or not.

**Comment by RyanHipkiss** [comment]
Thanks for the response. Will move.
