### ISSUE TITLE
Can't figure this out

### ISSUE THREAD

**Issue by RyanHipkiss** [GrahamCampbell/Laravel-GitHub#22]
Hi, 

I have downloaded this, but have no idea where to start for writing my calls to the API. 

I know it uses knplabs/php-github-api but it seems to change everything from there.

Any help?

**Comment by RyanHipkiss** [comment]
My bad tbh. 

It seemed like it was different, but infact its not.

**Comment by GrahamCampbell** [comment]
https://github.com/GrahamCampbell/Laravel-GitHub#real-examples
