### ISSUE TITLE
Accessing token from DB

### ISSUE THREAD

**Issue by newelement** [GrahamCampbell/Laravel-GitHub#25]
Greetings, I'm kinda new to the whole Laravel community, so please pardon if this is not the place to post this. I'm using OAuth2 to get my github token and I'm saving it in the users table. Using your class what would be the best way to access that token to make the API calls?

**Comment by coderstudiosdev** [comment]
This issue response should help: https://github.com/GrahamCampbell/Laravel-GitHub/issues/31
