### ISSUE TITLE
token coming from socialite

### ISSUE THREAD

**Issue by njames** [GrahamCampbell/Laravel-GitHub#31]
Hi Graham, I would like to use your api to manage repos but have the users tokens coming from socialite used instead of configured connections. Does the manager have the ability to do this or is this outside this scope of this product?

Thanks, 
Nigel

**Comment by GrahamCampbell** [comment]
Yes, you can do this. :)

I'd recommend using the factory class to do this. That's exactly how StyleCI works.

**Comment by GrahamCampbell** [comment]
```php
<?php

use GrahamCampbell\GitHub\GitHubFactory;

app(GitHubFactory::class)->make([/* */]);
```

**Comment by GrahamCampbell** [comment]
Maybe I need to put a couple of examples on the readme since it's such a common use case.

**Comment by njames** [comment]
Brilliant thanks for this @GrahamCampbell

**Comment by GrahamCampbell** [comment]
The way StyleCI does it is like this:

![image](https://cloud.githubusercontent.com/assets/2829600/17291235/a94f29aa-57da-11e6-86c4-75917710137d.png)

![image](https://cloud.githubusercontent.com/assets/2829600/17291261/c2e8793e-57da-11e6-8520-28aa08b59a5a.png)

Where the bottom line there is:

```php
return $this->factory->make(array_merge(['token' => $token, 'method' => 'token', 'cache' => true, 'backoff' => true], $options));
```

**Comment by njames** [comment]
Thanks Graham, very generous of you to share that.

**Comment by jacobzlogar** [comment]
Once i've created a client like this:
`            $client = app(GitHubFactory::class)->make(['token' => $user->github_token, 'method' => 'token', 'cache' => true]);
`
should i be able to access it through your github face like so:
` GitHub::$client->organizations() ` ?

**Comment by GrahamCampbell** [comment]
No, you can't use the facade with the instance you've created. You;ll need to keep track of that instance yourself.

**Comment by jacobzlogar** [comment]
`$token = $user->github_token;
            $client = new \Github\Client();
            $client->authenticate($token, 'http_token');
            dd($client->organizations());` correct me if i'm wrong but this is essentially the same thing as `Github::me()->organizations()` correct?

**Comment by jacobzlogar** [comment]
`$token = $user->github_token;
$client = new \Github\Client();
$client->authenticate($token, 'http_token');
dd($client->organizations());`
is essentially the same as
`GitHub::me()->organizations()`
right?

**Comment by jacobzlogar** [comment]
this might be a really stupid question, but is this correct?
```
$token = $user->github_token;
$client = new \Github\Client()->authenticate($token, 'http_token');
dd($client->organizations());
```
is the same thing as 
`Github::me()->organizations();`
right?

**Comment by jacobzlogar** [comment]
```$user = Auth::user();
            $token = $user->github_token;
            $client = new \Github\Client();
            $client->authenticate($token, 'http_token');
            dd($client->api('current_user')->organizations());```
The difference between my code and the facade is that the facade creates the httpclient with current_user as a parameter and i was trying to access the clients organizations without a current user, which don't exist. Thank you graham

**Comment by jamesaspence** [comment]
@GrahamCampbell I just wanted to say a few things:

1) you're awesome! Thanks for writing all the things you write!
2) Thanks for this example! I hope you end up adding this to the readme, as it is immensely helpful :)
