### ISSUE TITLE
how can I download blob files which are bigger than 1MB

### ISSUE THREAD

**Issue by omidmaldar** [GrahamCampbell/Laravel-GitHub#33]
I've tried this, 
`$fileContent = GitHub::repo('git-data')->contents()->download($this->owner, $this->repo, $path, $ref);`
I tried it by git and gitData also but every time I got this error. I also tried show() method with no progress.

> This API returns blobs up to 1 MB in size. The requested blob is too large to fetch via the API, but you can use the Git Data API to request blobs up to 100 MB in size

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. I'm not entirely sure. This package is mearly a wrapper around the real API package, which is over in a different repo, so feel free to get in touch with them. Feel free to pull me into that new issue if you need anything.

**Comment by omidmaldar** [comment]
thanks for your reply, sure. I'll do that.
