### ISSUE TITLE
about a warning i got from composer

### ISSUE THREAD

**Issue by akramabdulrahman** [GrahamCampbell/Laravel-GitHub#42]
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
could i just fork the project  , work with guzzlehttp and apply fixes wherever the calling method differs and do a pull request !? 
i am not an average contibutor to projects on github but am trying to be ! i'll use this package to make a cool project for searching repositories on github :dancers:

**Comment by vinkla** [comment]
Please see #32

**Comment by GrahamCampbell** [comment]
This will be fixed in 5.x of this package.

**Comment by GrahamCampbell** [comment]
Infact, this is already in progress.
