### ISSUE TITLE
issue create loops forever. 

### ISSUE THREAD

**Issue by Tjoosten** [GrahamCampbell/Laravel-GitHub#43]
Hi Graham, 

Thanks for the package. But i found a bug in your package.

if i do this in laravel. 

    public function pushGithub($fid)
    {
        // Get the report data:
        $report = Errors::find($fid);

        // Set the push data:
        $push['title'] = "Platform issue nr. $report->id";
        $push['body']  = $report->melding;

        // Github push hook.
        Github::issue()->create('Tjoosten', 'handicap-manifesto', $push, 1);

        return redirect()->back(302);
    }

The issue creation keeps on going. And spam the issue tracker on github.

**Comment by GrahamCampbell** [comment]
Thanks, but don't see how this relates to my package?

**Comment by GrahamCampbell** [comment]
The issue is with your redirect I assume?

**Comment by Tjoosten** [comment]
Indeed. srry for the bad issue report. And thanks for the quick response.

**Comment by GrahamCampbell** [comment]
np :)
