### ISSUE TITLE
Getting token from db?

### ISSUE THREAD

**Issue by m1guelpf** [GrahamCampbell/Laravel-GitHub#46]
I have the github token in my db. It can be accessed using
```
use Auth;
$user = Auth::user();
$token = $user->token;
```
As (I think) you can't use some functions in config files, how can I archieve that?

**Comment by GrahamCampbell** [comment]
You won't want to use config files here. Just directly use the factory class. :)

**Comment by GrahamCampbell** [comment]
```php
$gh = app('github.factory')->make(['token' => Auth::user()->token, 'method' => 'token']);
```

**Comment by m1guelpf** [comment]
@GrahamCampbell So I can't define main connection with database token?
Also, how do I use that $gh var in a controller?

**Comment by GrahamCampbell** [comment]
> Also, how do I use that $gh var in a controller?

That was just a code example. Just put that code in the controller.

**Comment by GrahamCampbell** [comment]
If you read through the source code and the tests in this package, it should all make sense.

**Comment by coderstudiosdev** [comment]
This issue and response may also help, did for me: https://github.com/GrahamCampbell/Laravel-GitHub/issues/31

**Comment by Daniel15** [comment]
I'm not sure if having "fat models" is a bad practice with Laravel, but I added this to my `User` model:
```php
  public function createGithubClient(): \Github\Client {
    return app('github.factory')->make([
      'token' => $this->github_token,
      'method' => 'token',
    ]);
  }
```

**Comment by tnylea** [comment]
Here's my solution. I created a middleware to dynamically change the `main` connection token. In my app, I am making a hard assumption that every user is authenticated with Github. Here's the Middleware:

```
<?php

namespace App\Http\Middleware;

use Closure;

class SetGithubToken
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        if(!auth()->guest()){
            config(['github.connections.main.token' => auth()->user()->gh_token]);
        }

        return $next($request);
    }
}
```

> Note: I stored the token in a column called `gh_token` instead of `token`.

I've then added that middleware to the end of my `web` middleware group inside of `App\Http\Kernel.php`:

```
protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            // \Illuminate\Session\Middleware\AuthenticateSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
            \App\Http\Middleware\SetGithubToken::class,
        ],

        'api' => [
            'throttle:60,1',
            'bindings',
        ],
    ];
```

Now, if a user is authenticated I can run the following:

```
dd(GitHub::me()->organizations());
```

And it will print out the user organizations 👍 

Hope this helps someone else out.

And @GrahamCampbell, dude you are every where. Thanks for this package I use many of your other ones as well.

**Comment by GrahamCampbell** [comment]
That's certainly a way to do it, however updating the config at runtime in this way feels like a hack. Config should really be treated as read-only in most scenarios, otherwise things just get confusing for people in the future looking at the codebase.

If you want to use the facade, you can do:

```
GitHub::getFactory()->make(['token' => Auth::user()->token, 'method' => 'token']);
```
