### ISSUE TITLE
Cache?

### ISSUE THREAD

**Issue by m1guelpf** [GrahamCampbell/Laravel-GitHub#47]
How do we configure and use cache?
Thank you!

**Comment by GrahamCampbell** [comment]
Set the confic key to either true, or a positive integer. :)

**Comment by GrahamCampbell** [comment]
Set the config key to either true, or the name of the laravel cache connector you want to use.

https://github.com/GrahamCampbell/Laravel-GitHub/blob/master/config/github.php#L45
https://github.com/GrahamCampbell/Laravel-GitHub/blob/master/src/GitHubFactory.php#L85-L87

**Comment by GrahamCampbell** [comment]
Make sure you also install `adewithlove/illuminate-psr-cache-bridge`.
