### ISSUE TITLE
Config setting to env setting. 

### ISSUE THREAD

**Issue by Tjoosten** [GrahamCampbell/Laravel-GitHub#48]
I was wondering. Can we just set the config variables (Credentails github), To the default `.env` file in github. 
Now there are need to fill in in the provided config file. So users can push their credentials by accident.

**Comment by m1guelpf** [comment]
@Tjoosten We can! See, for example, my Laragit project config:
https://github.com/m1guelpf/laragit/blob/dev/config/eloquent-oauth.php

**Comment by GrahamCampbell** [comment]
Yes, just publish the config file as described in the readme, and then update the published file to read from your environment. For example, in one of my apps, the `config/github.php` file looks like:

![image](https://cloud.githubusercontent.com/assets/2829600/21620779/e2168f0c-d1ed-11e6-82e1-cc127af48b97.png)

**Comment by Tjoosten** [comment]
But can you just it enabled by default in the package?

**Comment by GrahamCampbell** [comment]
No, because I don't want to force people to call "env" by default. It's easy to opt-in, but harder to opt-out.
