### ISSUE TITLE
[Question] Is there webhook support?

### ISSUE THREAD

**Issue by bkuhl** [GrahamCampbell/Laravel-GitHub#54]
Is there any webhook support here to assist with being notified when a new issue or pull request is added?

**Comment by GrahamCampbell** [comment]
No, as with the spirit of the rest of the library. You get back plain php arrays from the api methods, similar to a raw parse of the github webhook data on your own.

If you're looking to validate the signature of the hook, you can do something like this:

```php
$token = 'your secret token';

list($algo, $sig) = explode('=', Request::header('X-Hub-Signature'));

$hash = hash_hmac($algo, Request::getContent(), $token);

if (!hash_equals((string) $hash, (string) $sig)) {
    // ...
}

```
