### ISSUE TITLE
Getting 'Bad Credentials' when trying to use this

### ISSUE THREAD

**Issue by mdunbavan** [GrahamCampbell/Laravel-GitHub#6]
Hi @GrahamCampbell,

Just installed this with composer on laravel 4 and setup the config like so:

```
'default' => 'main',

    /*
    |--------------------------------------------------------------------------
    | GitHub Connections
    |--------------------------------------------------------------------------
    |
    | Here are each of the connections setup for your application. Example
    | configuration has been included, but you may add as many connections as
    | you would like.
    |
    */

    'connections' => [
        'main' => [
            'token'   => ' d3a0ec2f14a77bcfc39699ed8c3546714b6782a5',
        ],
    ],
```

I set all this up in the github settings for applications and created an app and auth token:

![screen shot 2015-03-03 at 20 29 54](https://cloud.githubusercontent.com/assets/671281/6471640/afe40c00-c1e4-11e4-8d46-345c7ce58797.png)

```
GitHub::me()->organizations();
```

When I try to access some data I get this:

'Bad credentials'

What could it be?

**Comment by GrahamCampbell** [comment]
Which version>

**Comment by GrahamCampbell** [comment]
Oh, I see. You need to use a "personal access token". They're different from application level ones.

**Comment by GrahamCampbell** [comment]
https://github.com/blog/1509-personal-api-tokens

**Comment by GrahamCampbell** [comment]
If your token bad been working, github would have been showing 1 user for your application even before you started using it with my package.

**Comment by mdunbavan** [comment]
Ah yeah i did that i am working locally so I think the callback url might be the issue here...
