### ISSUE TITLE
Issues inviting new collaborator to organisation

### ISSUE THREAD

**Issue by project24retry** [GrahamCampbell/Laravel-GitHub#69]
Hello to you, thanks for making this awsome package ! I just have one small issue using it, I am trying to invite news collaborators to my organisation but I get error not found I have posted on [stackoverflow](https://stackoverflow.com/questions/47948501/invite-new-collaborator-github-api-laravel-php) I was wondering if this was maybe a known issue. Thanks ahead.

**Comment by GrahamCampbell** [comment]
Thanks, but this package itself is just a wrapper. You are best submitting a concise issue on the upstream repo, detailing the issue.
