### ISSUE TITLE
repository lists incomplete

### ISSUE THREAD

**Issue by sdeering** [GrahamCampbell/Laravel-GitHub#7]
Hi, quick question. When I call for a list of repos for a user the list returned is incomplete seems to cut off at 20 total.

```
GitHub::api('user')->repositories($username);
```

Is there anyway I can get it to return the entire list? thanks

**Comment by GrahamCampbell** [comment]
Yeh, you need to use pagination.

**Comment by GrahamCampbell** [comment]
https://github.com/KnpLabs/php-github-api/blob/master/doc/result_pager.md

**Comment by GrahamCampbell** [comment]
Does this do the job?

```php
<?php

namespace Foo\Bar;

use Github\ResultPager;
use GrahamCampbell\GitHub\GitHubManager;

class Baz
{
    protected $client;
    protected $paginator;

    public function __constructor(GitHubManager $manager)
    {
        $this->client = $manager->connection();
        $this->paginator = new ResultPager($this->client);
    }

    public function repos($username)
    {
        return $this->paginator->fetchAll($this->client->user(), 'repositories', [$username]);
    }
}
```

**Comment by sdeering** [comment]
I replaced it with this and it works sweet now thanks mate!

```
        $client = new \Github\Client();
        $paginator = new \Github\ResultPager($client);
        return $paginator->fetchAll($client->user(), 'repositories', [$username]);
```

**Comment by GrahamCampbell** [comment]
You're going to want to create the client using my manager, like I did in my example, otherwise the authentication isn't going to happen.

**Comment by sdeering** [comment]
Ok but i'm confused as to where the GitHubManager $manager is provided to the constructor function.

**Comment by GrahamCampbell** [comment]
Through dependency injection.

**Comment by sdeering** [comment]
Is there any way you can use Facades here instead of dependency injection?

**Comment by GrahamCampbell** [comment]
Yes, but I wouldn't recommend it. Why don't you want to use dependency injection?

**Comment by sdeering** [comment]
I'd like to but it's not working maybe the GitHubManager class is not being auto loaded

**Comment by sdeering** [comment]
I think this should return the whole list. And maybe have a second function or options to return a paginated list.

```
GitHub::api('user')->repositories($username);
```

**Comment by GrahamCampbell** [comment]
> I'd like to but it's not working maybe the GitHubManager class is not being auto loaded

It works for me. We even have tests in this repo to show that it does work. What does your code look like?

**Comment by sdeering** [comment]
I think it's because I'm doing some funky stuff with controller instances so I can access functions between controllers (base controllers wont help here). This function is creating a GitHubController so it can be accessed on another controller.

```
  public function __construct() {

      //bind and create some controllers to use thier functions
      App::bind('GitHubController', function($app)
      {
          return new GitHubController();
      });
      $this->GitHubController = App::make('GitHubController');

  }
```

I've tried doing this but didn't work.

```
  public function __construct (GitHubManager $manager) {

      //bind and create some controllers to use thier functions
      App::bind('GitHubController', function($app) use ($manager)
      {
          return new GitHubController($manager);
      });
      $this->GitHubController = App::make('GitHubController');

  }
```

Then in the GitHubController exactly like you suggested.

```
  protected $client;
  protected $paginator;

  public function __construct(GitHubManager $manager)
  {
      // dd($manager);
      $this->client = $manager->connection();
      $this->paginator = new ResultPager($this->client);
  }
```

**Comment by GrahamCampbell** [comment]
Wow, you're doing this totally wrong, lol.

**Comment by GrahamCampbell** [comment]
`return new GitHubController();` is never going to work, is it?

**Comment by GrahamCampbell** [comment]
What you want is `return new GitHubController($app['github']->connection());`

**Comment by GrahamCampbell** [comment]
Then update the constructor to look like this:

```php
    public function __construct(Client $client)
    {
        $this->client = $client;
        $this->paginator = new ResultPager($client);
    }
```

**Comment by sdeering** [comment]
Wow, that's fixed it mate. Your a legend for helping me out there much appreciated.
Thanks heaps

**Comment by GrahamCampbell** [comment]
No problem. :)
