### ISSUE TITLE
Setting private access token

### ISSUE THREAD

**Issue by barooney** [GrahamCampbell/Laravel-GitHub#8]
Hi there!

I'm trying to set a private access token I acquired beforehands to request private repositories.

```php
Github::authenticate(Auth::user()->github_token, null, 'http_token');
```

But somehow, I am doing something wrong, because

```php
var_dump(Github::api('user')->repositories($username));
```

only shows public repositories. Am I missing something?

**Comment by GrahamCampbell** [comment]
Please ask on https://github.com/KnpLabs/php-github-api. Also, note that private repos from orgs won't show up from that command - a limitation from GitHub, though this will actually be changed soon by GitHub.

**Comment by coderstudiosdev** [comment]
This helped me: https://github.com/GrahamCampbell/Laravel-GitHub/issues/31
