### ISSUE TITLE
Laravel 5.8 Version

### ISSUE THREAD

**Issue by AdrianHL** [GrahamCampbell/Laravel-GitHub#86]
Hi,

First thanks for this package. I have seen there are changes to support Laravel 5.8 in master branch but no version has been released with these changes. I'd hope to see a release soon as this is the only package blocking the Laravel upgrade in one of our projects.

Thanks in advance

**Comment by BlueTeck** [comment]
Same here 🤔

**Comment by fridzema** [comment]
For me it just works in 5.8 what problems do you have?

**Comment by BlueTeck** [comment]
The latest tagged version does not allow illuminate 5.8 packages (if you use the latest master without any tag it seems to be fine).

https://github.com/GrahamCampbell/Laravel-GitHub/blob/master/composer.json#L14

vs

https://github.com/GrahamCampbell/Laravel-GitHub/blob/v7.6.0/composer.json#L14

**Comment by GrahamCampbell** [comment]
Will be released today. :)
