### ISSUE TITLE
Dynamic connections

### ISSUE THREAD

**Issue by saeedvaziry** [GrahamCampbell/Laravel-GitHub#91]
Is there possibility to set connection on fly? of course without using laravel `config` helper

like bellow:

    Github::connection([
        'token' => 'foo',
        'method' => 'token'
    ]);

**Comment by GrahamCampbell** [comment]
Yes, absolutely. You can do:

```php
Github::getFactory()->make([
    'token' => 'foo',
    'method' => 'token'
])`
```

Alternatively, just resolve the connection factory from the container (by whatever means you like, directly, injection, whatever) and call `make` on it directly.

**Comment by saeedvaziry** [comment]
@GrahamCampbell Thanks. It worked fine.
