### ISSUE TITLE
JWT Token Generation

### ISSUE THREAD

**Issue by ellisio** [GrahamCampbell/Laravel-GitHub#98]
Hey folks,

I'm looking to utilize this project's JWT connection. However, since the JWT requires an `exp`, what is your preferred method to generating a JWT before making a request?

Since you guys are expecting `connections.jwt.token` to be set, are you just creating tokens with expirations way in the future?

Or are you generating a token on the fly before each request and calling `authenticate($newToken, Client::AUTH_JWT)`?

Cheers

**Comment by ellisio** [comment]
Never mind, I think I figured this out.

```
$token = $github->connection('private')->apps()->createInstallationToken($installationId);
$github->connection('token')->authenticate(['token' => $token]);
```

Only thing I would like to change is the forced `file://` in `PrivateAuthenticator`. I want to store our PEM as an envvar on Vapor, and this is preventing that.

**Comment by GrahamCampbell** [comment]
> Only thing I would like to change is the forced file:// in PrivateAuthenticator. I want to store our PEM as an envvar on Vapor, and this is preventing that.

Could you send a PR to clarify what you mean, and I'll take a look.

**Comment by GrahamCampbell** [comment]
Thanks for the PR. With the new implementation, you can now pass "key" with the raw key content, rather than "keyPath" with the location of the key on disk. :)

**Comment by GrahamCampbell** [comment]
Example config file, which I think will work for you on envoyer:

```php
<?php

return [

    'default' => 'main',

    'connections' => [

        'main' => [
            'method' => 'private',
            'appId'  => env('GITHUB_APP_ID'),
            'key'    => str_replace('\\n', "\n", env('GITHUB_PRIVATE_KEY')),
        ],

    ],

];
```

**Comment by ellisio** [comment]
@GrahamCampbell Thank you! Happy New Year!
